version: '3'
services:       
    prerender:
        build: .
        image: prerender-alpine
        container_name: prerender-alpine
        ports:
        - 8992:3000
        restart: unless-stopped
#    nginx:
#        image: nginx
#        container_name: nginx
#        ports:
#            - 80:80
#        restart: unless-stopped
#        volumes:
#           - /mnt/storage/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#           - /mnt/storage/nginx/cache/:/var/cache/nginx/
#           - /mnt/storage/nginx/ssl/:/etc/nginx/ssl/         
