version: '3'
services:
    prerender:
        image: tvanro/prerender-alpine
        ports:
        - 3000:3000
        environment:
        - MEMORY_CACHE=0
        - CACHE_MAXSIZE=1000
        - CACHE_TTL=6000
        - CACHE_ROOT_DIR=/mnt/prerender/cache 
        - CACHE_LIVE_TIME=15.552.000
        restart: unless-stopped
