version: '3'
services:
    prerender:
        build: .
        container_name: prerender-alpine
        ports:
        - 3000:3000
        environment:
        - MEMORY_CACHE=0
        - CACHE_MAXSIZE=1000
        - CACHE_TTL=6000
        - DISK_CACHE=1
        - CACHE_ROOT_DIR=/prerender/cache
        - CACHE_LIVE_TIME=15.552.000
        volumes: 
            - /solr/prerender/cache:/prerender/cache
        restart: unless-stopped
