version: '3'
services:
    prerender:
        build: .
        image: prerender-alpine
        container_name: prerender-alpine
        ports:
        - 3000:3000
        environment:
        - MEMORY_CACHE=${MEMORY_CACHE}
        - CACHE_MAXSIZE=${CACHE_MAXSIZE}
        - CACHE_TTL=${CACHE_TTL}
        - DISK_CACHE=${DISK_CACHE}
        - CACHE_ROOT_DIR=${CACHE_ROOT_DIR}
        - CACHE_LIVE_TIME=${CACHE_LIVE_TIME}
        volumes: 
            - /solr/prerender/cache:/prerender/cache
        restart: unless-stopped
